### PR TITLE
Fix multiline parsing

### PR DESCRIPTION
**Pull request by donfiguerres**
This extension was not working properly in my environment and doing this fixed it for me. I'm not sure what the expected behavior from `line.character` was but it was not giving me the last character position. using `Position.range.end.character` fixed it for me.

However, I'm not sure yet how to deal with the failing tests in my environment. If you could give me some guidance then I would be more than happy to update this PR.

### CODE REVIEW

**Comment by nickjmiller** [comment]
To test it, you'll want to run the tests through the "Run and Debug" tab in vscode. There should be an `Extension Tests` launch configuration. I need to add that to the README somewhere

**Comment by donfiguerres** [comment]
Thanks! I'll try to work on this next week.

**Comment by ilolis** [comment]
Hello @donfiguerres. 

Does this pr solve the issue that exists when test cases have big names (as described [in this issue](https://github.com/nickjmiller/pytest-fixtures/issues/31))?

**Comment by donfiguerres** [comment]
> Hello @donfiguerres.
> 
> Does this pr solve the issue that exists when test cases have big names and fixtures exist in multiple lines (as described [in this issue](https://github.com/nickjmiller/pytest-fixtures/issues/31))?

Yes, but I have to make changes to this PR because I discovered that it breaks the existing behavior for functions with arguments in the same line and does not take into account inline comments.

**Comment by nickjmiller** [comment]
Ah I was able to figure out the issue after you brought this to my attention, it turns out I was refering to the wrong variable when calculating the next line, this should be fixed in the next release

**Comment by donfiguerres** [comment]
> Ah I was able to figure out the issue after you brought this to my attention, it turns out I was refering to the wrong variable when calculating the next line, this should be fixed in the next release

Great! Thanks @nickjmiller

**Pull request closed without merging**
